# =============================================================================
#  SHEOL // vconsole.conf
#  Linked to /etc/vconsole.conf
#  Console font for raw TTY (framebuffer console).
# =============================================================================

KEYMAP=us
FONT=ter-v22b
FONT_MAP=8859-1
